name       : fgt
version    : 0.4.9
release    : 1
source     :
    - https://github.com/gadomski/fgt/archive/refs/tags/v0.4.9.tar.gz : 677213957dff59d6f546855663670fa7991eb69fbe9caa9312c1296c2360fcb1
homepage   : https://www.gadom.ski/fgt/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : C++ library for fast Gauss transforms
description: |
    This is a C++ library for computing the Gauss transform using the direct method as well as a few shortcuts.
    The Gauss transform is a common operation that computes the per-point similarity between two data sets.
builddeps  :
    - pkgconfig(eigen3)
setup      : |
    %patch -p1 < $pkgfiles/build-shared-lib.patch
    %cmake_ninja \
        -DWITH_BENCH=ON \
        -DWITH_OPENMP=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DEIGEN3_INCLUDE_DIR=/usr/include/eigen3
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
